# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:           pretty
relative_permalinks: false


# Setup
title:               Prathap Rajaraman
tagline:             My Data Science Blog
url:                 https://prathapr91.github.io/
paginate:            5
baseurl:             https://prathapr91.github.io/

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Prathap Rajaraman
  url:               https://linkedin.com/in/prathaprajaraman/
  email:             prathap.rajaraman@gmail.com
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/prathapr91"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/prathaprajaraman/"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/prathapr91"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/prathapr91/"

# Custom vars
version:             2.1.0
github:
  repo:              https://github.com/prathapr91

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
